version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      # Variável de ambiente para conexão com o MongoDB (a URL usa o nome do serviço "mongo")
      - MONGO_URI=mongodb://mongo:27017/nestdb
    restart: always

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
